### PR TITLE
Update grid breakpoints

### PR DESCRIPTION
**Pull request by slavanga**

### CODE REVIEW

**Review by tuerlefl — COMMENTED** [review]
this will have impact on alle projects, can we do this? @kennydies

**Comment by kennydies** [comment]
> this will have impact on alle projects, can we do this? @kennydies

Yes indeed, this will impact all projects, but it is the desired behaviour according to Nicolai (multiple times in bugherd). Therefore i think it makes sense to adjust it globally. Thoughts?

**Comment by slavanga** [comment]
We would have to check the impact on project basis (for existing projects) and overwrite the styles where needed.

**Comment by tuerlefl** [comment]
ok, then let's do it :)

**Pull request merged**
