### PR TITLE
Chal/feat/formscrolltoinvalid

### PR DESCRIPTION
**Pull request by kennydies**

### CODE REVIEW

**Review by mariuskueng — COMMENTED** [review]
I may have asked this before, but this was not working, correct?
`$($(element).parents('form').first()[0]).find('.has-error button, .error').focus();`

**Comment by kennydies** [comment]
> I may have asked this before, but this was not working, correct?
> `$($(element).parents('form').first()[0]).find('.has-error button, .error').focus();`

This would work too. Is it cleaner than the code above?

**Comment by mariuskueng** [comment]
I guess? The previous code uses selector chaining, which a rarely used in this way.
Although I still don't understand way `.first().children` doesn't work...

You decide what you like better!

**Comment by mariuskueng** [comment]
Now there are 2 selectors 😆:

```js
$($(element).parents('form').first()[0]).find('.has-error button, .error').focus();
$(element).parents('form').first()[0].$('.has-error button, .error').focus();
```

**Review by mariuskueng — APPROVED** [review]

**Pull request merged**
